apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mathtrail-infra-local

manifests:
  rawYaml:
    - manifests/kafka-cluster.yaml

deploy:
  kubectl:
    defaultNamespace: mathtrail
  helm:
    releases:
      - name: postgres
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: postgresql
        namespace: mathtrail
        createNamespace: true
        valuesFiles:
          - values/postgresql-values.yaml
        wait: false

      - name: redis
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: redis
        namespace: mathtrail
        createNamespace: true
        valuesFiles:
          - values/redis-values.yaml
        wait: false

      - name: strimzi
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: strimzi-kafka-operator
        namespace: mathtrail
        createNamespace: true
        valuesFiles:
          - values/strimzi-values.yaml
        wait: true

      - name: traffic-manager
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: telepresence-oss
        namespace: ambassador
        createNamespace: true
        valuesFiles:
          - values/telepresence-values.yaml
        wait: true

profiles:
  - name: postgres
    patches:
      - op: remove
        path: /manifests
    deploy:
      helm:
        releases:
          - name: postgres
            repo: https://MathTrail.github.io/charts/charts
            remoteChart: postgresql
            createNamespace: true
            valuesFiles:
              - values/postgresql-values.yaml
            wait: true

  - name: redis
    patches:
      - op: remove
        path: /manifests
    deploy:
      helm:
        releases:
          - name: redis
            repo: https://MathTrail.github.io/charts/charts
            remoteChart: redis
            createNamespace: true
            valuesFiles:
              - values/redis-values.yaml
            wait: true

  - name: kafka
    manifests:
      rawYaml:
        - manifests/kafka-cluster.yaml
    deploy:
      helm:
        releases:
          - name: strimzi
            repo: https://MathTrail.github.io/charts/charts
            remoteChart: strimzi-kafka-operator
            createNamespace: true
            valuesFiles:
              - values/strimzi-values.yaml
            wait: true

  - name: telepresence
    patches:
      - op: remove
        path: /manifests
    deploy:
      helm:
        releases:
          - name: traffic-manager
            repo: https://MathTrail.github.io/charts/charts
            remoteChart: telepresence-oss
            namespace: ambassador
            createNamespace: true
            valuesFiles:
              - values/telepresence-values.yaml
            wait: true
