apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-local

requires:
  # Bring up Postgres first so dependent services can start after it is ready.
  - configs:
      - postgres
  - configs:
      - pgbouncer
      - redis
      - kafka

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: postgres

deploy:
  helm:
    releases:
      - name: postgres
        chartPath: charts/postgres
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: redis

deploy:
  helm:
    releases:
      - name: redis
        chartPath: charts/redis
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka

deploy:
  helm:
    releases:
      - name: kafka
        chartPath: charts/kafka
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: pgbouncer

deploy:
  helm:
    releases:
      - name: pgbouncer
        chartPath: charts/pgbouncer
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true
