apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-local

requires:
  # Bring up Postgres first so dependent services can start after it is ready.
  - configs:
      - postgres
  - configs:
      - redis
      - kafka
      - telepresence
      - vault
      - external-secrets
      - vault-init

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: postgres

deploy:
  helm:
    releases:
      - name: postgres
        repo: "{{.CHARTS_REPO}}"
        remoteChart: postgresql
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        valuesFiles:
          - values/postgresql-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: redis

deploy:
  helm:
    releases:
      - name: redis
        repo: "{{.CHARTS_REPO}}"
        remoteChart: redis
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        valuesFiles:
          - values/redis-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka

manifests:
  rawYaml:
    - manifests/kafka-cluster.yaml

deploy:
  kubectl:
    defaultNamespace: "{{.NAMESPACE}}"
  helm:
    releases:
      - name: strimzi
        repo: "{{.CHARTS_REPO}}"
        remoteChart: strimzi-kafka-operator
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        valuesFiles:
          - values/strimzi-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: telepresence

deploy:
  helm:
    releases:
      - name: traffic-manager
        repo: "{{.CHARTS_REPO}}"
        remoteChart: telepresence-oss
        namespace: ambassador
        createNamespace: true
        valuesFiles:
          - values/telepresence-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: vault

deploy:
  helm:
    releases:
      - name: vault
        repo: "{{.CHARTS_REPO}}"
        remoteChart: vault
        namespace: vault
        createNamespace: true
        valuesFiles:
          - values/vault-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: external-secrets

deploy:
  helm:
    releases:
      - name: external-secrets
        repo: "{{.CHARTS_REPO}}"
        remoteChart: external-secrets
        namespace: external-secrets
        createNamespace: true
        valuesFiles:
          - values/external-secrets-values.yaml
        wait: true

---
# vault-init deploys into the same namespace as postgres (where the Postgres secret lives).
# The Job waits for Vault to be ready, then configures the Database Secrets Engine and K8s auth.
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: vault-init

manifests:
  rawYaml:
    - manifests/vault-init-job.yaml
    - manifests/cluster-secret-store.yaml

deploy:
  kubectl:
    defaultNamespace: "{{.NAMESPACE}}"
