apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: mathtrail-infra-local

manifests:
  rawYaml:
    - manifests/kafka-cluster.yaml

deploy:
  kubectl:
    defaultNamespace: mathtrail
  helm:
    releases:
      - name: postgres
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: postgresql
        namespace: mathtrail
        createNamespace: true
        valuesFiles:
          - values/postgresql-values.yaml
        wait: false

      - name: redis
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: redis
        namespace: mathtrail
        createNamespace: true
        valuesFiles:
          - values/redis-values.yaml
        wait: false

      - name: strimzi
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: strimzi-kafka-operator
        namespace: mathtrail
        createNamespace: true
        valuesFiles:
          - values/strimzi-values.yaml
        wait: true

      - name: traffic-manager
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: telepresence-oss
        namespace: ambassador
        createNamespace: true
        wait: true
