apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-local

requires:
  - configs:
      - postgres
      - redis
      - kafka
      - telepresence

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: postgres

deploy:
  helm:
    releases:
      - name: postgres
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: postgresql
        createNamespace: true
        valuesFiles:
          - values/postgresql-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: redis

deploy:
  helm:
    releases:
      - name: redis
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: redis
        createNamespace: true
        valuesFiles:
          - values/redis-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka

manifests:
  rawYaml:
    - manifests/kafka-cluster.yaml

deploy:
  kubectl: {}
  helm:
    releases:
      - name: strimzi
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: strimzi-kafka-operator
        createNamespace: true
        valuesFiles:
          - values/strimzi-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: telepresence

deploy:
  helm:
    releases:
      - name: traffic-manager
        repo: https://MathTrail.github.io/charts/charts
        remoteChart: telepresence-oss
        namespace: ambassador
        createNamespace: true
        valuesFiles:
          - values/telepresence-values.yaml
        wait: true
