apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-local

requires:
  # Bring up Postgres first so dependent services can start after it is ready.
  - configs:
      - postgres
  - configs:
      - pgbouncer
      - redis
      - kafka
      - vault-db-init

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: postgres

deploy:
  helm:
    releases:
      - name: postgres
        repo: "{{.CHARTS_REPO}}"
        remoteChart: postgresql
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        valuesFiles:
          - values/postgresql-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: redis

deploy:
  helm:
    releases:
      - name: redis
        repo: "{{.CHARTS_REPO}}"
        remoteChart: redis
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        valuesFiles:
          - values/redis-values.yaml
        wait: true

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kafka

manifests:
  rawYaml:
    - manifests/kafka-cluster.yaml

deploy:
  kubectl:
    defaultNamespace: "{{.NAMESPACE}}"
  helm:
    releases:
      - name: strimzi
        repo: "{{.CHARTS_REPO}}"
        remoteChart: strimzi-kafka-operator
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        valuesFiles:
          - values/strimzi-values.yaml
        wait: true



---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: pgbouncer

manifests:
  kustomize:
    paths:
      - manifests/pgbouncer

deploy:
  kubectl:
    defaultNamespace: "{{.NAMESPACE}}"

---
# vault-db-init creates per-namespace Vault database config and dynamic role.
# Requires vault-cluster-init (from infra/) to have run first.
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: vault-db-init

manifests:
  rawYaml:
    - manifests/vault-db-init-job.yaml

deploy:
  kubectl:
    defaultNamespace: "{{.NAMESPACE}}"
