# Redis local development values
# Bitnami Redis 25.3.2
# Values are nested under the dependency name (redis).

vaultPush:
  secretStore:
    name: vault-kv-backend
    kind: ClusterSecretStore
  refreshInterval: 1h

redis:
  architecture: standalone

  auth:
    enabled: true
    password: "mathtrail"

  master:
    persistence:
      enabled: true
      size: 1Gi
    resourcesPreset: "nano"
